# Generated by Django 5.2.8 on 2025-11-23 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('PLAYED', 'Played'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10, null=True)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('challenger_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_c1', to=settings.AUTH_USER_MODEL)),
                ('challenger_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_c2', to=settings.AUTH_USER_MODEL)),
                ('defender_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_as_d1', to=settings.AUTH_USER_MODEL)),
                ('defender_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_as_d2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
