# Generated by Django 5.2.8 on 2025-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(choices=[('EMAIL', 'Email/Password'), ('GOOGLE', 'Google OAuth')], default='EMAIL', help_text='Authentication provider used for this account', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google user ID (sub claim from OAuth)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_picture',
            field=models.URLField(blank=True, help_text="URL to user's Google profile picture", null=True),
        ),
    ]
