# Generated by Django 5.2.8 on 2025-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_auth_provider_profile_google_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional OAuth provider-specific data'),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_id',
            field=models.CharField(blank=True, db_index=True, help_text="OAuth provider's unique user ID (e.g., Google 'sub', Apple 'sub', etc.)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_picture',
            field=models.URLField(blank=True, help_text="URL to user's profile picture from OAuth provider", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(choices=[('EMAIL', 'Email/Password'), ('GOOGLE', 'Google OAuth'), ('APPLE', 'Apple Sign In'), ('FACEBOOK', 'Facebook Login')], default='EMAIL', help_text='Authentication provider used for this account', max_length=20),
        ),
    ]
